version: '2'

services:
  base-ubuntu:
    image: prius/base-ubuntu
    build:
      context: /home/prius/git/github.com/prius/dockerfiles/base-ubuntu/
      dockerfile: /home/prius/git/github.com/prius/dockerfiles/base-ubuntu/Dockerfile
    entrypoint: sleep infinity
    volumes:
      - "/home/prius/git/github.com/prius/ansible-playbooks:/etc/my/ansible"
      - "/home/prius/git/github.com/prius/dockerfiles/base-ubuntu/files/etc/my/ansible/manual/:/etc/my/ansible/manual/"
      - "/home/prius/.bashrc:/root/.bashrc"
      - "/home/prius/.vim:/root/.vim"
      - "/home/prius/.vimrc:/root/.vimrc"
